version: '3'
services:
  cron:
    container_name: cron
    image: wngusrud27/docker-cron
    restart: on-failure
    stdin_open: true
    tty: true
    volumes: 
      - ./:/app
    environment:
      - ACTIVE=Docker
      - TZ=Asia/Seoul

## docker-compose up -d
## docker exec -it cron /bin/bash 