version: '3'
services:
  cron:
    container_name: ybo_cron
    image: wngusrud27/docker-cron
    restart: on-failure
    stdin_open: true
    tty: true
    volumes: 
      - ./:/usr/src
    environment:
      - TZ=Asia/Seoul

## docker-compose up -d
## docker exec -it ybo_cron /bin/bash 