version: '3'
services:
  cron:
    container_name: ybo_cron
    build: ./
    restart: on-failure
    stdin_open: true
    tty: true
    volumes: 
      - ./:/app
    environment:
      - TZ=Asia/Seoul

# build image and run container
## docker-compose -f docker-compose-local.yml up -d --build 
## docker exec -it ybo_cron /bin/bash 

