version: '3'
services:
  cron:
    container_name: cron
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    stdin_open: true
    tty: true
    volumes: 
      - ./:/app
    environment:
      - ACTIVE=Docker
      - TZ=Asia/Seoul